import ServiceDetail from "@/components/ServiceDetail";

const printServices: Record<string, any> = {
  "business-cards": { title: "Business Cards", description: "Professional business cards that make a lasting impression. Perfect for networking, trade shows, and client meetings.", sizes: ["3.5\" x 2\"", "3.5\" x 2.125\""], materials: ["100lb Gloss Cover", "110lb Matte Cover", "Cardstock"], finishes: ["Gloss", "Matte", "Silk", "Spot UV"], pricing: [{ option: "250 Cards", price: "$25-45" }, { option: "500 Cards", price: "$35-65" }, { option: "1000 Cards", price: "$55-95" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What file format do you accept?", answer: "We accept PDF, AI, PSD, and TIFF files with 0.25\" bleed." }, { question: "How quickly can I get my cards?", answer: "Standard turnaround is 5-7 business days." }] },
  "brochures": { title: "Brochures", description: "Eye-catching brochures to showcase your business. Tri-fold, bi-fold, and custom sizes available.", sizes: ["8.5\" x 11\" (Tri-fold)", "8.5\" x 14\" (Bi-fold)"], materials: ["100lb Gloss Cover", "110lb Matte Cover"], finishes: ["Gloss", "Matte", "Satin"], pricing: [{ option: "100 Brochures", price: "$50-100" }, { option: "250 Brochures", price: "$90-150" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What is the standard tri-fold size?", answer: "8.5\" x 11\" when folded to 3.67\" x 11\"." }] },
  "flyers": { title: "Flyers", description: "Promote your business with high-quality flyers. Perfect for events, sales, and announcements.", sizes: ["8.5\" x 11\"", "5.5\" x 8.5\""], materials: ["24lb Uncoated", "80lb Gloss"], finishes: ["Gloss", "Matte"], pricing: [{ option: "100 Flyers", price: "$20-35" }, { option: "500 Flyers", price: "$55-95" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What's the most popular size?", answer: "8.5\" x 11\" is most popular for standard flyers." }] },
  "banners": { title: "Banners", description: "Large format banners for maximum visibility. Indoor and outdoor options with various materials.", sizes: ["2' x 4'", "3' x 6'", "4' x 8'"], materials: ["Vinyl Banner", "Mesh Banner"], finishes: ["Matte", "Gloss"], pricing: [{ option: "2' x 4'", price: "$35-60" }, { option: "3' x 6'", price: "$60-100" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What material for outdoor use?", answer: "Vinyl banners are UV-resistant and perfect for outdoor use." }] },
  "postcards": { title: "Postcards", description: "Cost-effective direct mail postcards. Perfect for marketing campaigns and customer outreach.", sizes: ["4\" x 6\"", "5\" x 7\""], materials: ["14pt Cardstock", "16pt Cardstock"], finishes: ["Glossy", "Matte"], pricing: [{ option: "250 Postcards", price: "$25-45" }, { option: "1000 Postcards", price: "$70-120" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Are postcards mailable?", answer: "Yes, 4x6 postcards are USPS-approved." }] },
  "letterhead": { title: "Letterhead", description: "Professional letterhead printing for your business correspondence.", sizes: ["8.5\" x 11\"", "8.5\" x 14\""], materials: ["24lb Bond", "28lb Bond"], finishes: ["Gloss", "Matte"], pricing: [{ option: "250 Sheets", price: "$30-50" }, { option: "1000 Sheets", price: "$80-130" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What paper weight is best?", answer: "28lb bond is standard, 32lb is heavier and more premium." }] },
  "envelopes": { title: "Envelopes", description: "Custom printed envelopes for professional mailing.", sizes: ["#10 (4.125\" x 9.5\")", "#9 (3.875\" x 8.875\")"], materials: ["24lb Bond", "28lb Bond"], finishes: ["Standard", "Window"], pricing: [{ option: "250 Envelopes", price: "$20-35" }, { option: "1000 Envelopes", price: "$60-100" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Most common size?", answer: "#10 envelope is the standard business envelope." }] },
  "labels": { title: "Labels", description: "Custom labels for products, shipping, and branding.", sizes: ["1\" x 1\"", "2\" x 2\"", "4\" x 6\""], materials: ["Glossy", "Matte", "Clear"], finishes: ["Permanent", "Removable"], pricing: [{ option: "100 Labels", price: "$15-30" }, { option: "1000 Labels", price: "$70-120" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Permanent vs removable?", answer: "Permanent is long-lasting, removable peels off cleanly." }] },
  "signs": { title: "Signs", description: "Professional signage for your business. Indoor and outdoor options.", sizes: ["12\" x 18\"", "18\" x 24\"", "24\" x 36\""], materials: ["Coroplast", "Vinyl", "PVC"], finishes: ["Matte", "Gloss"], pricing: [{ option: "10 Signs (Single)", price: "$50-100" }, { option: "10 Signs (Double)", price: "$80-150" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Best material for outdoor?", answer: "Vinyl or Coroplast are best for outdoor durability." }] },
  "posters": { title: "Posters", description: "Eye-catching posters for events and promotions.", sizes: ["11\" x 17\"", "18\" x 24\"", "24\" x 36\""], materials: ["Gloss Paper", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "10 Posters", price: "$25-50" }, { option: "50 Posters", price: "$90-180" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Most popular size?", answer: "18\" x 24\" is most popular for event posters." }] },
  "copies": { title: "Copies", description: "Professional document copying services. Black & white and color copying available.", sizes: ["8.5\" x 11\"", "8.5\" x 14\""], materials: ["20lb White", "Colored Paper"], finishes: ["Single-sided", "Double-sided"], pricing: [{ option: "B&W Copy (per page)", price: "$0.05-0.15" }, { option: "Color Copy (per page)", price: "$0.25-0.50" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What's the turnaround?", answer: "Most copy jobs completed same day or within hours." }] },
  "3d-printing": { title: "3D Printing", description: "Professional 3D printing services for prototypes and models.", sizes: ["Custom sizes"], materials: ["PLA", "ABS", "Resin"], finishes: ["Matte", "Glossy"], pricing: [{ option: "Small Model", price: "$20-50" }, { option: "Large Model", price: "$100-500" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What materials do you use?", answer: "We offer PLA, ABS, and Resin printing options." }] },
  "invitations": { title: "Invitations", description: "Custom printed invitations for events.", sizes: ["5\" x 7\"", "4\" x 6\""], materials: ["Cardstock", "Premium Paper"], finishes: ["Matte", "Gloss"], pricing: [{ option: "50 Invitations", price: "$25-50" }, { option: "250 Invitations", price: "$80-150" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Lead time?", answer: "Standard lead time is 5-7 business days." }] },
  "vehicle-graphics": { title: "Vehicle Graphics", description: "Professional vehicle wraps and graphics for your business.", sizes: ["Custom sizes"], materials: ["Vinyl Wrap", "Decals"], finishes: ["Matte", "Gloss"], pricing: [{ option: "Partial Wrap", price: "$500-1500" }, { option: "Full Wrap", price: "$2000-5000" }], image: "/service-digital-printing.jpg", faqs: [{ question: "How long do wraps last?", answer: "Quality wraps last 3-5 years depending on weather." }] },
  "calendars": { title: "Calendars", description: "Custom printed calendars for home or office.", sizes: ["11\" x 8.5\"", "8.5\" x 11\""], materials: ["Gloss Paper", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "25 Calendars", price: "$50-100" }, { option: "100 Calendars", price: "$150-250" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Turnaround time?", answer: "Calendars typically take 7-10 business days." }] },
  "custom-greeting-cards": { title: "Custom Greeting Cards", description: "Personalized greeting cards for any occasion.", sizes: ["5\" x 7\"", "4\" x 6\""], materials: ["Cardstock", "Premium Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "25 Cards", price: "$15-30" }, { option: "100 Cards", price: "$40-80" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Personalization options?", answer: "We offer variable data printing for personalized cards." }] },
  "every-door-direct-mail": { title: "Every Door Direct Mail", description: "EDDM campaigns for broad market reach without mailing list requirements.", sizes: ["5\" x 8\"", "6\" x 9\""], materials: ["Cardstock", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "500 Pieces", price: "$100-200" }, { option: "5000 Pieces", price: "$800-1200" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What is EDDM?", answer: "Every Door Direct Mail allows you to reach all addresses in a ZIP code without a mailing list." }] },
  "stationery": { title: "Business Stationery", description: "Complete business stationery packages including letterhead and envelopes.", sizes: ["8.5\" x 11\""], materials: ["Bond Paper", "Premium Paper"], finishes: ["Matte", "Gloss"], pricing: [{ option: "Letterhead + Envelopes", price: "$75-150" }, { option: "Full Stationery Set", price: "$150-300" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What's included?", answer: "Typically includes letterhead, envelopes, and business cards." }] },
  "yard-signs": { title: "Yard Signs", description: "Durable yard signs for real estate, events, and promotions.", sizes: ["24\" x 18\"", "36\" x 24\""], materials: ["Coroplast", "Foam Board"], finishes: ["Matte", "Gloss"], pricing: [{ option: "10 Signs", price: "$30-60" }, { option: "50 Signs", price: "$120-200" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Are frames included?", answer: "Metal frames are available for additional cost." }] },
  "blueprints": { title: "Blueprints", description: "Professional blueprint printing for architectural and construction documents.", sizes: ["24\" x 36\"", "36\" x 48\""], materials: ["Blueprint Paper", "Matte Paper"], finishes: ["Standard"], pricing: [{ option: "Per blueprint", price: "$5-15" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What formats do you accept?", answer: "We accept PDF, DWG, and other CAD file formats." }] },
  "canvas-wraps": { title: "Canvas Wraps", description: "High-quality canvas wraps for artwork and photography.", sizes: ["8\" x 10\"", "12\" x 16\"", "24\" x 36\""], materials: ["Canvas", "Premium Canvas"], finishes: ["Matte", "Gloss"], pricing: [{ option: "Small Canvas", price: "$30-60" }, { option: "Large Canvas", price: "$100-300" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Wrapped on sides?", answer: "Yes, sides are wrapped with your image for a professional look." }] },
  "direct-mail": { title: "Direct Mail", description: "Complete direct mail services from design to delivery.", sizes: ["5\" x 8\"", "6\" x 9\""], materials: ["Cardstock", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "500 Pieces", price: "$200-400" }, { option: "5000 Pieces", price: "$1200-2000" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Do you handle mailing?", answer: "Yes, we offer complete mailing services including postage." }] },
  "stickers": { title: "Custom Stickers", description: "Die-cut custom stickers in any shape and size.", sizes: ["2\" x 2\"", "3\" x 3\"", "Custom"], materials: ["Vinyl", "Paper"], finishes: ["Glossy", "Matte"], pricing: [{ option: "100 Stickers", price: "$20-40" }, { option: "500 Stickers", price: "$60-120" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Die-cut available?", answer: "Yes, any custom shape available as die-cut stickers." }] },
  "presentation-materials": { title: "Presentation Materials", description: "Professional presentation materials for your business meetings.", sizes: ["8.5\" x 11\"", "11\" x 17\""], materials: ["Gloss Paper", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "50 Presentations", price: "$75-150" }, { option: "250 Presentations", price: "$250-500" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Binding options?", answer: "We offer comb, spiral, and saddle stitch binding." }] },
  "carbonless-forms": { title: "Carbonless Forms", description: "Multi-part carbonless forms for order forms and receipts.", sizes: ["8.5\" x 11\"", "5.5\" x 8.5\""], materials: ["Carbonless Paper"], finishes: ["Standard"], pricing: [{ option: "500 Forms", price: "$75-125" }, { option: "2500 Forms", price: "$250-400" }], image: "/service-digital-printing.jpg", faqs: [{ question: "How many parts?", answer: "We offer 2, 3, 4, and 5-part carbonless forms." }] },
  "door-hangers": { title: "Door Hangers", description: "Cost-effective door hangers for local marketing campaigns.", sizes: ["8.5\" x 11\"", "3.5\" x 8.5\""], materials: ["Cardstock", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "100 Hangers", price: "$20-40" }, { option: "500 Hangers", price: "$60-120" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Perforated?", answer: "Yes, standard door hangers include perforation." }] },
  "forms": { title: "Custom Forms", description: "Customized forms for business operations.", sizes: ["8.5\" x 11\"", "5.5\" x 8.5\""], materials: ["Bond Paper", "Cardstock"], finishes: ["Standard"], pricing: [{ option: "500 Forms", price: "$50-100" }, { option: "2500 Forms", price: "$150-300" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Numbering available?", answer: "Yes, sequential numbering available for forms." }] },
  "newsletters": { title: "Newsletters", description: "Professional newsletter printing for regular customer communication.", sizes: ["8.5\" x 11\"", "11\" x 17\""], materials: ["Gloss Paper", "Matte Paper"], finishes: ["Gloss", "Matte"], pricing: [{ option: "250 Newsletters", price: "$75-150" }, { option: "1000 Newsletters", price: "$200-400" }], image: "/service-digital-printing.jpg", faqs: [{ question: "How often?", answer: "We handle print-on-demand for monthly or quarterly newsletters." }] },
  "promotional-products": { title: "Promotional Products", description: "Custom branded promotional products for marketing.", sizes: ["Various"], materials: ["Various"], finishes: ["Various"], pricing: [{ option: "Branded Items", price: "Starting at $2 per item" }, { option: "Minimum Order", price: "100 pieces" }], image: "/service-digital-printing.jpg", faqs: [{ question: "What products available?", answer: "Pens, mugs, t-shirts, hats, tote bags, and more." }] },
  "trade-show-displays": { title: "Trade Show Displays", description: "Custom trade show displays and booth materials.", sizes: ["10' x 10'", "20' x 20'"], materials: ["Fabric", "Vinyl", "Aluminum"], finishes: ["Various"], pricing: [{ option: "Tradeshow Booth", price: "$2000-5000" }, { option: "Display Banner", price: "$300-1000" }], image: "/service-digital-printing.jpg", faqs: [{ question: "Design included?", answer: "Yes, custom design included with booth rental." }] },
};

export default async function PrintServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const service = printServices[slug];

  if (!service) {
    return (
      <div className="bg-white py-16">
        <div className="max-w-6xl mx-auto px-4 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Service Not Found</h1>
          <p className="text-lg text-gray-600 mb-8">
            The print service "{slug}" is currently unavailable. Please contact us for details.
          </p>
          <a href="/#services" className="inline-block bg-[#003d6b] text-white font-semibold px-6 py-3 rounded hover:bg-[#66bb6a] transition-colors">
            View All Services
          </a>
        </div>
      </div>
    );
  }

  return <ServiceDetail {...service} />;
}
